INSERT INTO Tags (Name) VALUES ('New Arrival') ON CONFLICT(Name) DO NOTHING;
INSERT INTO Tags (Name) VALUES ('Popular') ON CONFLICT(Name) DO NOTHING;
INSERT INTO Tags (Name) VALUES ('Sale') ON CONFLICT(Name) DO NOTHING;
INSERT INTO Tags (Name) VALUES ('Limited Edition') ON CONFLICT(Name) DO NOTHING;
